# Generated by Django 5.0.2 on 2024-02-08 07:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("domain", models.CharField(max_length=120, unique=True)),
                ("local", models.BooleanField(default=True)),
                ("blocked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("handle", models.CharField(blank=True, max_length=120)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("actor_type", models.CharField(default="person", max_length=15)),
                ("blocked", models.BooleanField(default=False)),
                ("profile_url", models.URLField(blank=True)),
                ("outbox_url", models.URLField(blank=True)),
                ("inbox_url", models.URLField(blank=True)),
                ("private_key", models.TextField(blank=True)),
                ("public_key", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actors",
                        to="activitypub.instance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Following",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("status", models.CharField(default="requested", max_length=15)),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="activitypub.actor",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="activitypub.actor",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="following",
            constraint=models.UniqueConstraint(
                condition=models.Q(("handle", ""), _negated=True),
                fields=("follower", "followed"),
                name="activitypub_following_unique_following",
            ),
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("handle", ""), _negated=True),
                fields=("instance", "handle"),
                name="activitypub_actor_unique_handle",
            ),
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("instance", "user"),
                name="activitypub_actor_unique_local_user",
            ),
        ),
    ]
