# Generated by Django 5.0.2 on 2024-02-09 10:17

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("handle", models.CharField(max_length=120)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("group", "Group"),
                            ("service", "Service"),
                            ("application", "Application"),
                            ("organization", "Organization"),
                        ],
                        default="person",
                        max_length=15,
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("profile_url", models.URLField()),
                ("outbox_url", models.URLField()),
                ("inbox_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("domain", models.CharField(max_length=120, unique=True)),
                ("blocked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "activity_object_id",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("status", models.CharField(default="requested", max_length=15)),
                (
                    "followed_local",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "followed_remote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_followers",
                        to="activitypub.actor",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actor",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actors",
                to="activitypub.instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("followed_local__isnull", False),
                            ("followed_remote__isnull", True),
                        ),
                        models.Q(
                            ("followed_local__isnull", True),
                            ("followed_remote__isnull", False),
                        ),
                        _connector="OR",
                    )
                ),
                name="activitypub_follow_must_be_either_local_or_remote",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("followed_local__isnull", False)),
                fields=("follower", "followed_local"),
                name="activitypub_follow_unique_follow_local",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("followed_remote__isnull", False)),
                fields=("follower", "followed_remote"),
                name="activitypub_follow_unique_follow_remote",
            ),
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("handle", ""), _negated=True),
                fields=("instance", "handle"),
                name="activitypub_actor_unique_handle",
            ),
        ),
    ]
