# Generated by Django 5.0.2 on 2024-02-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="local",
        ),
        migrations.AlterField(
            model_name="actor",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("group", "Group"),
                    ("service", "Service"),
                    ("application", "Application"),
                    ("organization", "Organization"),
                ],
                default="person",
                max_length=15,
            ),
        ),
    ]
