# Generated by Django 5.0.2 on 2024-02-09 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="activitypub_follow_unique_follow_local",
        ),
        migrations.RemoveConstraint(
            model_name="follow",
            name="activitypub_follow_unique_follow_remote",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="follower",
        ),
        migrations.AddField(
            model_name="follow",
            name="follower_local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="follower_remote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed",
                to="activitypub.actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("followed_local__isnull", False), ("follower_local__isnull", False)
                ),
                fields=("follower_local", "followed_local"),
                name="activitypub_follow_unique_follow_local_to_local",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("followed_remote__isnull", False),
                    ("follower_local__isnull", False),
                ),
                fields=("follower_local", "followed_remote"),
                name="activitypub_follow_unique_follow_local_to_remote",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("followed_local__isnull", False),
                    ("follower_remote__isnull", False),
                ),
                fields=("follower_remote", "followed_local"),
                name="activitypub_follow_unique_follow_remote_to_local",
            ),
        ),
    ]
