# Generated by Django 5.0.2 on 2024-02-09 11:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "activitypub",
            "0002_remove_follow_activitypub_follow_unique_follow_local_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="activity_object_id",
        ),
        migrations.AddField(
            model_name="follow",
            name="activitypub_object_id",
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
