# Generated by Django 5.0.2 on 2024-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0002_remove_instance_local_alter_actor_actor_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="actor",
            name="activitypub_actor_unique_local_user",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="public_key",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="user",
        ),
        migrations.AlterField(
            model_name="actor",
            name="inbox_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="actor",
            name="outbox_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="actor",
            name="profile_url",
            field=models.URLField(),
        ),
    ]
