# Generated by Django 5.0.2 on 2024-02-09 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0003_remove_follow_activity_object_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="activitypub_object_id",
            new_name="object_id",
        ),
        migrations.AddField(
            model_name="follow",
            name="domain",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("object_id", ""), ("domain", ""), _connector="OR"),
                    _negated=True,
                ),
                fields=("object_id", "domain"),
                name="activitypub_follow_unique_object_id_domain",
            ),
        ),
    ]
