# Generated by Django 5.0.2 on 2024-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0004_rename_activitypub_object_id_follow_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="follow",
            name="status",
            field=models.CharField(default="created", max_length=15),
        ),
    ]
