# Generated by Django 5.0.2 on 2024-02-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0001_initial"),
        ("releases", "0002_release_search_trigger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="releases",
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="releases.release",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "release"),
                name="collections_collectionitem_unique_collection_item",
            ),
        ),
    ]
