# Generated by Django 5.0.2 on 2024-02-19 11:43

import django.contrib.postgres.search
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv_show", "TV Show")],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("original_title", models.CharField(blank=True, max_length=120)),
                ("tagline", models.TextField(blank=True)),
                ("overview", models.TextField(blank=True)),
                ("tmdb_id", models.BigIntegerField()),
                ("imdb_id", models.CharField(blank=True, max_length=12)),
                ("homepage", models.URLField(blank=True)),
                ("backdrop_url", models.URLField(blank=True)),
                ("poster_url", models.URLField(blank=True)),
                ("language", models.CharField(default="en", max_length=2)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "runtime",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Runtime (minutes)"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                ("num_seasons", models.PositiveIntegerField(default=0)),
                ("num_episodes", models.PositiveIntegerField(default=0)),
                (
                    "countries",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="releases.genre"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("category", "tmdb_id"),
                name="releases_release_unique_tmdb_id_category",
            ),
        ),
    ]
