# Generated by Django 5.0.2 on 2024-02-19 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER release_update_search_trigger
BEFORE INSERT OR UPDATE OF title, original_title, search_vector ON releases_release
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english', title, original_title);
UPDATE releases_release SET search_vector = NULL;""",
            reverse_sql="DROP TRIGGER IF EXISTS release_update_search_trigger ON releases_release;",
        ),
    ]
