# Generated by Django 5.0.2 on 2024-02-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("category", "tmdb_id"),
                name="releases_release_unique_tmdb_id_category",
            ),
        ),
    ]
