# Generated by Django 5.0.2 on 2024-02-09 10:17

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activitypub", "0001_initial"),
        ("people", "0002_alter_person_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("original_title", models.CharField(blank=True, max_length=120)),
                ("tagline", models.TextField(blank=True)),
                ("overview", models.TextField(blank=True)),
                ("tmdb_id", models.BigIntegerField(unique=True)),
                ("imdb_id", models.CharField(blank=True, max_length=12)),
                ("homepage", models.URLField(blank=True)),
                ("backdrop", models.URLField(blank=True)),
                ("poster", models.URLField(blank=True)),
                ("language", models.CharField(default="en", max_length=2)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "runtime",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Runtime (minutes)"
                    ),
                ),
                (
                    "countries",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
                ("genres", models.ManyToManyField(blank=True, to="movies.genre")),
            ],
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=120)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies_as_crew_member",
                        to="people.person",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_members",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies_as_cast_member",
                        to="people.person",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast_members",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "activity_object_id",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("url", models.URLField(blank=True)),
                ("comment", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activitypub.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="movies.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
