# Generated by Django 5.0.2 on 2024-02-09 11:41

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0003_remove_follow_activity_object_id_and_more"),
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="activity_object_id",
        ),
        migrations.AddField(
            model_name="review",
            name="activitypub_object_id",
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
        migrations.AddField(
            model_name="review",
            name="activitypub_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("dispatched", "Dispatched")],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("actor__isnull", True), ("user__isnull", False)),
                        models.Q(("actor__isnull", False), ("user__isnull", True)),
                        _connector="OR",
                    )
                ),
                name="movies_review_actor_or_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("activitypub_object_id", "user"),
                name="movies_review_unique_local_object_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actor__isnull", False)),
                fields=("activitypub_object_id", "actor"),
                name="movies_review_unique_remote_object_id",
            ),
        ),
    ]
