# Generated by Django 5.0.2 on 2024-02-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0001_initial"),
        ("movies", "0002_movie_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="castmember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="credits.person"
            ),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="credits.person"
            ),
        ),
    ]
