# Generated by Django 5.0.2 on 2024-02-10 09:18

from django.db import migrations

GENRES = [
    {"id": 28, "name": "Action"},
    {"id": 12, "name": "Adventure"},
    {"id": 16, "name": "Animation"},
    {"id": 35, "name": "Comedy"},
    {"id": 80, "name": "Crime"},
    {"id": 99, "name": "Documentary"},
    {"id": 18, "name": "Drama"},
    {"id": 10751, "name": "Family"},
    {"id": 14, "name": "Fantasy"},
    {"id": 36, "name": "History"},
    {"id": 27, "name": "Horror"},
    {"id": 10402, "name": "Music"},
    {"id": 9648, "name": "Mystery"},
    {"id": 10749, "name": "Romance"},
    {"id": 878, "name": "Science Fiction"},
    {"id": 10770, "name": "TV Movie"},
    {"id": 53, "name": "Thriller"},
    {"id": 10752, "name": "War"},
    {"id": 37, "name": "Western"},
]


def _create_genres(apps, schema_editor):
    Genre = apps.get_model("movies.Genre")
    Genre.objects.bulk_create(
        [Genre(tmdb_id=item["id"], name=item["name"]) for item in GENRES],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_remove_review_movies_review_unique_local_object_id_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=_create_genres,
            reverse_code=migrations.RunPython.noop,
        )
    ]
