# Generated by Django 5.0.2 on 2024-02-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activitypub", "0002_remove_instance_local_alter_actor_actor_type"),
        ("movies", "0004_review_modified_alter_review_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activitypub.actor",
            ),
        ),
    ]
