# Generated by Django 5.0.2 on 2024-02-10 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_tmdb_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="backdrop",
            new_name="backdrop_url",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="poster",
            new_name="poster_url",
        ),
    ]
