repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
            exclude: bundle.js|bundle.js.map|bundle.css
          - id: end-of-file-fixer
            exclude: bundle.js|bundle.js.map|bundle.css
          - id: check-builtin-literals
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: destroyed-symlinks
          - id: detect-private-key
          - id: file-contents-sorter
            args: ["--ignore-case", "--unique"]
            exclude: .gitignore|.dockerignore|requirements[-\w]*.txt
    - repo: local
      hooks:
          - id: rustywind
            name: rustywind Tailwind CSS class linter
            language: node
            additional_dependencies:
                - rustywind@0.21.0
            entry: rustywind
            args: [--write]
            types_or: [html]
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.9.0
      hooks:
          - id: shellcheck
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.3.0"
      hooks:
          - id: ruff
            args: ["--fix"]
          - id: ruff-format
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            files: \.(|js|css)$
            exclude: bundle.js|bundle.js.map|bundle.css
    - repo: https://github.com/Riverside-Healthcare/djLint
      rev: v1.34.1
      hooks:
          - id: djlint-django
            args: ["--lint", "--reformat"]
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
          - id: hadolint-docker
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.1
      hooks:
          - id: pyupgrade
            args: [--py311-plus]
    - repo: https://github.com/adamchainz/django-upgrade
      rev: "1.16.0"
      hooks:
          - id: django-upgrade
            args: [--target-version, "5.0"]
