# Generated by Django 5.0.2 on 2024-02-10 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_alter_person_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="profile",
            new_name="profile_url",
        ),
    ]
