# Generated by Django 5.0.2 on 2024-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogathons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogathon",
            old_name="submitted",
            new_name="published",
        ),
        migrations.AddField(
            model_name="proposal",
            name="response",
            field=models.TextField(blank=True),
        ),
    ]
