# Generated by Django 5.0.2 on 2024-02-29 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogathons", "0002_alter_proposal_participant_alter_proposal_proposal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="state_changed_at",
            new_name="status_changed_at",
        ),
    ]
