# Generated by Django 5.0.2 on 2024-02-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogathons", "0003_rename_state_changed_at_proposal_status_changed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="blog_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="entry",
            name="blog_url",
            field=models.URLField(),
        ),
    ]
