# Generated by Django 5.0.2 on 2024-03-02 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_review_in_reply_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="in_reply_to",
            new_name="parent",
        ),
    ]
