# Generated by Django 5.0.2 on 2024-03-05 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_bio_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Link",
        ),
    ]
