# Generated by Django 5.0.2 on 2024-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Unspecified"), (1, "Female"), (2, "Male")]
                    ),
                ),
                ("profile_url", models.URLField(blank=True)),
            ],
        ),
    ]
