# Generated by Django 5.0.2 on 2024-02-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Unspecified"), (1, "Female"), (2, "Male")]
                    ),
                ),
                ("profile_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actors",
                        to="releases.release",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast_credits",
                        to="credits.person",
                    ),
                ),
            ],
        ),
    ]
