# Generated by Django 5.0.2 on 2024-02-17 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0002_crewmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="castmember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast_members",
                to="credits.person",
            ),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_members",
                to="credits.person",
            ),
        ),
    ]
