# Generated by Django 5.0.2 on 2024-02-20 15:41

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0003_person_search_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="castmember",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="crewmember",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
