# Generated by Django 5.0.2 on 2024-02-20 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0004_castmember_search_vector_crewmember_search_vector"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER castmember_update_search_trigger
BEFORE INSERT OR UPDATE OF character, search_vector ON credits_castmember
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english', character);
UPDATE credits_castmember SET search_vector = NULL;""",
            reverse_sql="DROP TRIGGER IF EXISTS castmember_update_search_trigger ON credits_castmember;",
        ),
    ]
