# Generated by Django 5.0.2 on 2024-02-20 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0005_cast_member_search_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER crewmember_update_search_trigger
BEFORE INSERT OR UPDATE OF job, search_vector ON credits_crewmember
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english', job);
UPDATE credits_crewmember SET search_vector = NULL;""",
            reverse_sql="DROP TRIGGER IF EXISTS crewmember_update_search_trigger ON credits_crewmember;",
        ),
    ]
